[project]
name = "tfm-svmiw"
version = "0.1.0"
description = "Single View Metrology in the Wild Master's Thesis helper scripts"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "pre-commit>=4.2.0",
]
