flowchart TB

%% =====================================================
%% STYLE DEFINITIONS
%% =====================================================
classDef dataset fill:#EAF2FF,stroke:#4A90E2,stroke-width:2,color:#111;
classDef dl fill:#FFF3E8,stroke:#F5A623,stroke-width:2,color:#111;
classDef classical fill:#E8F6EE,stroke:#27AE60,stroke-width:2,color:#111;
classDef eval fill:#F4ECFF,stroke:#8E44AD,stroke-width:2,color:#111;

%% =====================================================
%% TRAINING STAGE
%% =====================================================

subgraph T["Etapa de Entrenamiento del modelo"]

direction TB

A1["COCO-Scale dataset"]
A2["Pano360 dataset"]

A1 --> B
A2 --> B

B["Nueva implementación del modelo de metrología monocular"]

B --> C["Código de entrenamiento semi-supervisado, minimizando el error de re-proyección"]

C --> D["Modelo entrenado final"]

end

D --> D1

%% =====================================================
%% INFERENCE STAGE
%% =====================================================

subgraph I["Procedimiento de Inferencia"]

direction TB

E["Conjunto de datos con alturas conocidas "]

%% ---------- Classical branch ----------

subgraph C1["Calibración de cámara clásica"]

direction TB

F["Procedimiento de calibración manual de cámara"]

F --> G["Obtención de parámetros intrínsecos y extrínsecos"]

G --> H["Re-proyección geométrica 3D-2D"]

H --> I1["Estimación de altura (método clásico)"]

end

%% ---------- DL branch ----------

subgraph D1["Inferencia por aprendizaje profundo"]

direction TB

J["Inferencia utilizando modelo SVMIW"]

J --> K["Estimación de altura (método por aprendizaje)"]

end

E --> C1
E --> D1

L["Comparación Experimental"]
end

I1 --> L
K --> L




%% =====================================================
%% CLASSES
%% =====================================================

class A1,A2,E dataset;
class B,C,D,J,K dl;
class F,G,H,I1 classical;
class L,M eval;

style T fill:none,stroke:#666,stroke-width:2px
style I fill:none,stroke:#666,stroke-width:2px
style C1 fill:none,stroke:#999,stroke-width:1.5px
style D1 fill:none,stroke:#999,stroke-width:1.5px
